DATA:
    ROOT: '../PED2/'
    TRAIN_FILE: 'configs/ped2/PED2_train.txt'
    VAL_FILE: 'configs/ped2/PED2_test.txt'
    DATASET: traffic
    NUM_CLIPS: 16
    NUM_FRAMES: 5
    FRAME_INTERVAL: 6
    NUM_CLASSES: 2
    LABEL_LIST: 'configs/ped2/ped2_2_labels.csv'
    FILENAME_TMPL: '{:03}.tif'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 8
ADV_TRAIN:
    EPS: 0.5
