DATA:
    ROOT: '../MSAD/'
    TRAIN_FILE: 'configs/msad/MSAD_train.txt'
    VAL_FILE: 'configs/msad/MSAD_test.txt'
    DATASET: msad
    NUM_CLIPS: 16
    NUM_FRAMES: 5
    FRAME_INTERVAL: 6
    NUM_CLASSES: 2
    LABEL_LIST: 'configs/msad/msad_2_labels.csv'
    FILENAME_TMPL: 'frame_{:04}.jpg'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 8
ADV_TRAIN:
    EPS: 0.5
