DATA:
    ROOT: '../TAD/'
    TRAIN_FILE: 'configs/traffic/TAD_train.txt'
    VAL_FILE: 'configs/traffic/TAD_test.txt'
    DATASET: traffic
    NUM_CLIPS: 16
    NUM_FRAMES: 5
    FRAME_INTERVAL: 6
    NUM_CLASSES: 2
    LABEL_LIST: 'configs/traffic/traffic_2_labels.csv'
    FILENAME_TMPL: '{}.jpg'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 8
    AUTO_RESUME: False
ADV_TRAIN:
    EPS: 0.5
    LOSS: 'ce'
    PSEUDO_LABEL: True
    PSEUDO_ANOMALY: True
